### ISSUE TITLE
build errors at core/

### ISSUE THREAD

**Issue by lcheng62** [square/subzero#132] opened 2019-12-11 06:21 UTC
I followed the steps below based on https://subzero.readthedocs.io/en/master/running_without_hsm/:

The final "make" command failed with some directory missing errors. 

# build the C code, using testnet transactions.
cd ../core
mkdir build
cd build
TARGET=dev CURRENCY=btc-testnet cmake ../
make

This-MacBook-Pro:build vagrant$ make
[  1%] Generating ../nanopb/generator/proto/plugin_pb2.py
/Users/vagrant/work/test2/subzero/core/build/nanopb/generator/proto: warning: directory does not exist.
Could not make proto path relative: /Users/vagrant/work/test2/subzero/core/build/nanopb/generator/proto/plugin.proto: No such file or directory
make[2]: *** [nanopb/generator/proto/plugin_pb2.py] Error 1
make[1]: *** [proto/CMakeFiles/PlutusProtos.dir/all] Error 2
make: *** [all] Error 2

I also tried the solution of https://github.com/square/subzero/issues/35, 

git fetch origin pull/37/head:pull_37
git checkout pull_37
git submodule update --init --recursive

However, it doesn't help.

I'm not using docker build. It is just a vagrant mac build.

Hope someone can help.

**Comment by alokmenghrajani** [comment] 2019-12-11 07:19
Did you git clone recursively? The project has two submodules.

**Comment by lcheng62** [comment] 2019-12-11 17:34
yes I did followed the steps of https://subzero.readthedocs.io/en/master/running_without_hsm/ and included "recursive" at git clone. Below is my last few commands in history which exactly matched the instruction.

$ make
[  1%] Generating ../nanopb/generator/nanopb_generator.py, ../nanopb/generator/proto/nanopb.proto, ../nanopb/generator/proto/plugin.proto
[  2%] Generating ../nanopb/generator/proto/plugin_pb2.py
/Users/vagrant/work/test3/subzero/core/build/nanopb/generator/proto: warning: directory does not exist.
Could not make proto path relative: /Users/vagrant/work/test3/subzero/core/build/nanopb/generator/proto/plugin.proto: No such file or directory
make[2]: *** [nanopb/generator/proto/plugin_pb2.py] Error 1
make[1]: *** [proto/CMakeFiles/SubzeroProtos.dir/all] Error 2
make: *** [all] Error 2
$ history | tail
  253  git clone --recursive https://github.com/square/subzero.git
  254  cd subzero/
  255  cd java/
  256  mvn package
  257  cd ../core/
  258  mkdir build
  259  cd build/
  260  TARGET=dev CURRENCY=btc-testnet cmake ../
  261  make
  262  history | tail

**Comment by alokmenghrajani** [comment] 2019-12-13 23:26
I'll get a fresh laptop next week and see if I can repro / figure out what's going on.

**Comment by alokmenghrajani** [comment] 2019-12-20 23:14
Can you please try to change `#!/usr/bin/env python` to `#!/usr/bin/env python3` at the top of core/build/nanopb/generator/nanopb_generator.py? I'm unable to reproduce this exact issue, but I did notice that we are using python in some cases and we are probably better off always using python3.

**Comment by alokmenghrajani** [comment] 2019-12-20 23:42
When you say vagrant mac build, is Mac OS X the host operating system? Are you running linux inside?

**Comment by lcheng62** [comment] 2019-12-20 23:57
I'm using a mac OS as vagrant virtualbox under a mac OS machine. I still got the same error as below. BTW, I managed to build this project with a Linux ubuntu 18. But I'd be interested to see it works for mac.

This-MacBook-Pro:build vagrant$ head -n 5 nanopb/generator/nanopb_generator.py 
#!/usr/bin/env python3

from __future__ import unicode_literals

'''Generate header file for nanopb from a ProtoBuf FileDescriptorSet.'''
This-MacBook-Pro:build vagrant$ make
[  1%] Generating ../nanopb/generator/proto/plugin_pb2.py
Could not make proto path relative: /Users/vagrant/work/test4/subzero/core/build/nanopb/generator/proto/plugin.proto: No such file or directory
make[2]: *** [nanopb/generator/proto/plugin_pb2.py] Error 1
make[1]: *** [proto/CMakeFiles/SubzeroProtos.dir/all] Error 2
make: *** [all] Error 2

**Comment by alokmenghrajani** [comment] 2019-12-21 01:37
Sorry, I don't know what's going on. Feel free to open a PR if you are able to fix the build. https://github.com/nanopb/nanopb/blob/master/README.md might be a good place to start?

You might also have better luck using a pre-built nanopb binary from https://jpa.kapsi.fi/nanopb/download/.

**Comment by alokmenghrajani** [comment] 2020-01-02 18:44
I'm going to close this out. The most reliable way to build things is to use Docker.

**Closed by alokmenghrajani** 2020-01-02 18:44 UTC

**Comment by lcheng62** [comment] 2020-01-09 18:48
@alokmenghrajani Happy 2020! Sorry for the late response. Here is my procedure of building subzero at ubuntu18. Feel free to edit it and copy it to the project README or maybe subzero document at https://subzero.readthedocs.io/en/master/, such that the Linux users can also have a quick reference for installation and get benefit from subzero.

- Some preparation steps to update the system with necessary toolchains.

```
sudo apt-get update
sudo apt-get install openssh-server
sudo apt-get install autoconf automake libtool curl make cmake g++ unzip python
```
- Install protobuf. 
(I was stumped by this step mainly due to the mismatch versions. Now I explicitly specifies v3.6.1 and build it from scratch. Things go smoothly.)
```
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz
tar -xzvf protobuf-all-3.6.1.tar.gz  
cd protobuf-3.6.1/
./configure
make
make check
sudo make install
sudo ldconfig
protoc --version
```
- Now install subzero. Note the recursive option as multiple projects will be cloned.
```
cd ..
git clone --recursive https://github.com/square/subzero.git
cd subzero/
cd core/
mkdir build
cd build/
sudo apt-get install python-protobuf
nano ~/.bashrc
# add this line at the top of ~/.bashrc -> alias python=python3
source ~/.bashrc
sudo apt install python-pip
pip install google.cloud.bigquery
pip install google.cloud.storage
TARGET=dev CURRENCY=btc-testnet cmake ../
make
```
